[project]
name = "beaverton-creek"
version = "0.1.0"
description = "Calculations for Beaverton Creek"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "forallpeople",
    "handcalcs",
    "ipython",
    "jupyter",
    "matplotlib",
    "numpy",
    "pandas",
    "pandas-stubs",
    "polars",
    "PyniteFEA[all]",
    "sectionproperties",
    "scipy",
    "sympy" 
]

[dependency-groups]
dev = ["mypy", "ruff"]

[tool.ruff.lint]
ignore = ["F821"]